import Section1 from "@/components/Section1";
import styles from "@/styles/Section1.module.css";
import Head from "next/head";

export default function Features() {
  return (
    <>
      <Head>
        <title>Features</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className={styles.mt}>
        <Section1 />
        <Section1 />
        <Section1 />
        <Section1 />
      </div>
    </>
  );
}
