import Navbar from "@/components/Navbar/navbar";
import Section1 from "@/components/Section1/section1";
import styles from "@/styles/Section1.module.css";
import Head from "next/head";

export default function Test() {
  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar/>
      <div className={styles.mt}>
        <Section1 />
      </div>
    </>
  );
}
